---
apiVersion: v1
kind: Service
metadata:
  name: fabrc-chaincode
  labels:
    run: fabrc-chaincode
spec:
  selector:
    name: fabrc-chaincode
  ports:
  - protocol: TCP
    targetPort: 2375
    port: 2375
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabrc-chaincode
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fabrc-chaincode
  template:
    metadata:
      labels:
        name: fabrc-chaincode
    spec:
      volumes:
      - name: dockervolume
        persistentVolumeClaim:
          claimName: docker-pvc
      containers:
      - name: fabrc-chaincode
        securityContext:
          privileged: true
        image: "docker:stable-dind"
        ports:
        - containerPort: 2375
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        volumeMounts:
        - mountPath: /var/lib/docker
          name: dockervolume